### ISSUE TITLE
a problem with mzmine3 exporting data running on ISFRAG

### ISSUE THREAD

**Issue by Judyzyw** [HuanLab/ISFrag#2]
MZmine version: 3.4.27
R \RStudio\ Rtools version: 4.3.0

We only want to use the results exported by MZmine to see the presence of ISF in the alingnment ID we detected, but in the LEVEL3 function, the parameter "ms1.files" was not previously defined, and looking at the "functions" of R found that it was included in the "XCMS.featuretable" function, and the example also gave the data processed using XCMS, we want to know, If you just enter .csv (aligned) exported from mzmine and .mzXML (64 files)  and don't rely on XCMS, can you run ISFrag successfully  and hopefully get a demo code.

Below is my running code.
```
`library(ISFrag)

MS1directory <- "H:/ZYW/co_objects_shandong/NEG/co_objects_neg_mzxml"
MS2directory <- "H:/ZYW/co_objects_shandong/NEG/co_objects_neg_mzxml"

ft_directory <- "H:/ZYW/co_objects_shandong/NEG/sep_isfrag"
ft_name_multi <- "sep_neg_isfrag.csv"

setwd(ft_directory)
head(read.csv(ft_name_multi, header = T, stringsAsFactors = F))
customFT <- custom.featuretable(ft_directory = ft_directory, ft_name = ft_name_multi)
head(customFT)

featureTable <- ms2.assignment(MS2directory = MS2directory, customFT = customFT)

MS1.files <- list.files(path = "H:/ZYW/co_objects_shandong/NEG/co_objects_neg_mzxml", pattern = ".mzXML")

level3 <- find.level3(MS1directory = MS1directory, MS1.files = MS1.files, featureTable = featureTable, type = "multi")
#The previous operation can be done, that is, the error is reported in this place
#Error in serialize(data, node$con) : error writing to connection

level2 <- find.level2(ISFtable = level3)
level1 <- find.level1(ISF_putative = level2)

results <- get.ISFrag.results(ISF_List = level1, featureTable = featureTable)
resultFT <- export.ISFrag.results(ISFresult = results)
write.csv(resultFT, file = "sep_isf_output.csv", row.names = F, col.names = T)`
```

**Comment by HuanLab** [comment]
Hi, 

Level 3 in-source fragments are recognized by their high chromatographic peak-peak correlation with the parent m/zs. To achieve the correlation analysis, we implemented MSnbase.R from XCMS to plot the EICs first and then calculate the correlation coefficient (ISFragfunctions_20211115.R, line 495 onward). 

It should be fine that you enter a .csv (aligned) exported from mzmine (make sure to follow the ISFrag input template) and .mzXML (or mzML) for ISFrag analysis. However, the level 3 decision has to be made after extracting and calculating EIC correlations using XCM. In other words, XCMS is not really used to do peak picking, but called (function: rawEIC()) to extract EICs for peak-peak correlation analysis. 

Let me know if you run into any error messages. I will be happy to provide further help.

**Comment by Judyzyw** [comment]
Thank you for your clarification, but I still have a few small puzzles:
1. I only have DDA data (64 files in.mxml format), so I set MS1directory and MS2directory to the same path, I wonder if this is reasonable;
2. I can export a.CSV file containing MS2 (Aligned) from mzmine3 or export a.csv file containing complete information (a portion without MS2 information), I wonder whether it would be effective to operate a.CSV file containing only MS2 in the R package
3. Following your advice, I added the command line of "xcmsFT" to the original code. I want to know if we should use a combination of XCMS and user-provided custom feature table or if we can run it successfully Using only the custom feature table
4. When I run the R package, I find that the command "level3 < -find.level3(MS1directory = MS1directory, MS1.files = MS1.files, When featureTable = featureTable, type = "multi"), R was running so many threads that my CPU usage reached 100% (my CPU has 64 cores and windows10 64bit). Is there any code instruction that can control the CPU proportion or thread number when the R package is running?

Here is my code
```
library(ISFrag)

# MS1directory specifies the full directory of the folder containing mzXML file(s).
MS1directory <- "F:/ZYW/shandong/NEG/mzmine3.4.27_output_neg/isfrag_sep/co_objects_neg_sep_mzml"
# MS2directory specifies the full directory of the folder containing DDA mzXML file(s).
MS2directory <- "F:/ZYW/shandong/NEG/mzmine3.4.27_output_neg/isfrag_sep/co_objects_neg_sep_mzml"

xcmsFT <- XCMS.featuretable(MS1directory = MS1directory, type = "multi", peakwidth = c(5,80))

# ft_directory specifies the directory of the custom csv file.
ft_directory <- "F:/ZYW/shandong/NEG/mzmine3.4.27_output_neg/isfrag_sep/co_objects_neg_sep_table"
# ft_name specifies the name of the custom csv file.
ft_name_multi <- "sep_neg_isfrag.csv"

setwd(ft_directory)
head(read.csv(ft_name_multi, header = T, stringsAsFactors = F))
# The add.features() function outputs a dataframe formatted feature table containing
customFT <- custom.featuretable(ft_directory = ft_directory, ft_name = ft_name_multi)
head(customFT)

# The ms2.tofeaturetable() function assigns MS2 spectra from the provided DDA files to the MS1 feature table. It returns a new feature table with additional columns containing MS2 fragment information.
# Using a combination of XCMS and user-provided custom feature table
featureTable <- ms2.assignment(MS2directory = MS2directory, customFT = customFT)
head(featureTable)

level3 <- find.level3(MS1directory = MS1directory, MS1.files = MS1.files, featureTable = featureTable, type = "multi")
level2 <- find.level2(ISFtable = level3)
level1 <- find.level1(ISF_putative = level2)

results <- get.ISFrag.results(ISF_List = level1, featureTable = featureTable)
resultFT <- export.ISFrag.results(ISFresult = results)
write.csv(resultFT, file = "sep_isf_output.csv", row.names = F, col.names = T)
```

**Comment by HuanLab** [comment]
Hi, here are my answers.
1. I only have DDA data (64 files in.mxml format), so I set MS1directory and MS2directory to the same path, I wonder if this is reasonable;
    Yes. it is correct

2. I can export a.CSV file containing MS2 (Aligned) from mzmine3 or export a.csv file containing complete information (a portion without MS2 information), I wonder whether it would be effective to operate a.CSV file containing only MS2 in the R package
   I am not sure whether it would be more effective. The current version would directly extract MS2 from the provided raw DDA data. 

3. Following your advice, I added the command line of "xcmsFT" to the original code. I want to know if we should use a combination of XCMS and user-provided custom feature table or if we can run it successfully Using only the custom feature table
   I don't think you need to create the xcmsFT. ISFrag directly reads the mz and RT information and look for its EIC in the raw LC-MS data. 


4. When I run the R package, I find that the command "level3 < -find.level3(MS1directory = MS1directory, MS1.files = MS1.files, When featureTable = featureTable, type = "multi"), R was running so many threads that my CPU usage reached 100% (my CPU has 64 cores and windows10 64bit). Is there any code instruction that can control the CPU proportion or thread number when the R package is running?
   Here we used a parallel processing. You can reduce the number of cores in the code for any of the functions.
![image](https://github.com/HuanLab/ISFrag/assets/52514403/02806acb-4c8c-48ea-9fa7-d8998355d111)

Let me know if you have further question.

**Comment by Judyzyw** [comment]
Thank you very much. I followed your advice and successfully ran this code. It took a long time to execute the command "LEVEL3". I even thought it couldn't run successfully, but in the end, it successfully exported. Thank you again for patiently answering my confusion.
<img width="709" alt="83003ae0442aaa559c60b386da677a5" src="https://github.com/HuanLab/ISFrag/assets/120540244/9c9e7bf0-b3cd-4729-a57a-c0522ccc8f1e">

I am currently using the one derived from mzmine3 that contains all the mass spectrum information（a portion without MS2 information）.CSV file. Of course, subsequent operations made its content conform to the conditions of ISFrag import. ( if you do not run the xcmsFT command, you need to add an additional line specifying MS1directory, otherwise the LEVEL3 command will not be executed. ) I found that alignment ID without MS2 spectrum information could also be calculated in the ISF result, and of course it would only stop at LEVEL2. Due to this discovery,  I want to try to make my result more concise if  inputa.CSV file containing only MS2 . Because data without MS2 spectrum information was not part of my data analysis.

**Comment by HuanLab** [comment]
Sure. That is a good idea. Let me know if you encounter any further questions.

**Comment by Judyzyw** [comment]
Hello, I was a little confused when I was thinking later. 
Generally speaking, when doing peak similarity assessment, in this case "pearson" correlation calculation in "level3 ", the calculation should be limited to the same sample peak, i.e., single chromatogram, but ISFrag can also act on multiple samples（aligned result）. In one same alignment ID, pearson correlation>0.8 for some samples, while pearson correlation<0.8 for others, and their corresponding precursor ions may be different. I have found such a situation in the results: Many alignment ID have been identified as multiple ions of level1 ISF. 
<img width="747" alt="77738d78482c442c3a616813b50478b" src="https://github.com/HuanLab/ISFrag/assets/120540244/b2abc2ed-1d9d-41ed-9937-60bd8e1329bf">
I would like to know the reason for this result and the principle of ISFrag's calculation when facing multiple samples. Do you have any suggestions?

**Comment by HuanLab** [comment]
Are you talking about the cases where F9669 <- Level_1 shows up twice (in row 1, column ISF_level)?

**Comment by Judyzyw** [comment]
Yes, in addition to this, there is also a problem: an ID is considered as level1 ISF of multiple precursor metabolites, but not as level1 ISF of a precursor metabolite

**Comment by HuanLab** [comment]
The redundant issue is a bug somewhere in the code. It basically prints out the same result twice but does not cause other problems. 

In terms of an ID is considered as level1 ISF of multiple precursor metabolites, rather than a single precursor, it might be that these multiple precursors are structurally related to each other. It happens that the ISF just fits for the criterial for all of them. You can manually take a look of the raw data if that makes sense.

**Comment by Judyzyw** [comment]
Ok, thanks for the answer, but I found a few questions:
Take level1 ISF identified in the first line (temporarily called ISF_A) as an example.
It was identified as level1 ISF of multiple precursor metabolites. I randomly selected several of its precursor metabolites, but found that m/z of ISF_A did not appear in MS2 spectrum of F36059. I would like to ask whether the MS2 spectrum of F36059 is the fusion of MS2 spectrum of multiple samples (I uploaded 3 samples) or the MS2 spectrum of one of the samples. Why the above situation? In addition, how to calculate pearson correlation coefficient in the same alignment ID in the case of multiple samples?Because the literature only mentions the PCC calculation of a single sample.
<img width="936" alt="13ac0d8051babca161dc7542a38188a" src="https://github.com/HuanLab/ISFrag/assets/120540244/43eb1824-9105-49ba-95d6-06673cc0dd27">
<img width="939" alt="443e4bee53d96d2ee954b6802c29a72" src="https://github.com/HuanLab/ISFrag/assets/120540244/7f693c7e-a174-41e3-af51-ace9de3d0db3">

**Comment by HuanLab** [comment]
The MS/MS should not be a fusion of multiple MS/MS. I will check with the students later when I am back from conference. 

Pearson correlation is calculated using the series of intensity values across the chromatographic peak. It is calculated from the sample of the most high MS signal. Multiple samples are not needed.

**Comment by Judyzyw** [comment]
Thank you for your reply, I appreciate it.

**Comment by HuanLab** [comment]
We checked many of our datasets, and all the level 1 ISF are in the MS/MS of the precursor. We feel that it is not possible that a confirmed level 1 ISF is outside the MS/MS data. Can you double check your sample files? Does that problem happen a lot in your testing?

**Comment by Judyzyw** [comment]
Ok, thanks for your work.
1.resultFT: I first found the substance with the most Number_Level1 by descending in "Number_Level1", that is, F74094 (Number_Level1=33), and his result was "F9669<-Level_1;F9669<-Level_1;F9670<-Level_1; F9670<-Level_1;F36059<-Level_1;F36061<-Level_1;F36063<-Level_1;F36065<-Level_1;F36070<-Level_1;F64584<-Level_1;F64586<-Level_1;F72326<-Level_1;F72327 <-Level_1; F72328<-Level_1;F72329<-Level_1;F72330<-Level_1;F72331<-Level_1;F72332<-Level_1;F72348<-Level_1;F72350<-Level_1;F72351<-Level_1;F72353<-Level_1;F7236 8<-Level_1; F72388<-Level_1;F72392<-Level_1;F72409<-Level_1;F72413<-Level_1;F72421<-Level_1;F72493<-Level_1;F72494<-Level_1;F72495<-Level_1;F72496<-Level_1;F7249 7<-Level_1” , this is the information of the "ISF_level" column, that is to say, F74094 is the ISF of the above 33 IDs.
<img width="758" alt="3dc73aef87c37a823ae49e5bbcabeb2" src="https://github.com/HuanLab/ISFrag/assets/120540244/1eacee7d-8836-43b6-9059-b59d59cb7fd1">
<img width="762" alt="5f6d6bb786bb2a86156620b9f4777f5" src="https://github.com/HuanLab/ISFrag/assets/120540244/0751571a-0353-4a29-a062-bbaabee6adae">
2.level 1: I selected one of the above IDs "F6970", and searched in the table of "level 1", then double-clicked to open the information of the ID "F6970", and found that the result of "F4097" here is "Level3 ", which is inconsistent with the information I got in "resultFT"
<img width="761" alt="5e6187f0f146854994244a0ae27a4a2" src="https://github.com/HuanLab/ISFrag/assets/120540244/89742485-122f-4783-895c-406223d2a0a5">
<img width="760" alt="5f0930cae8831344f4e5ce62f9abd29" src="https://github.com/HuanLab/ISFrag/assets/120540244/e1025191-d410-46d8-8402-353c18bc0567">
In this case, it is currently found that the result of this ID "F74094" is not normal, and no problems have been found in other data.

**Comment by Judyzyw** [comment]
**Continuing with the previous idea, I hoped to only input IDs containing MS2 information to reduce workload, but some situations occurred：**
 when I ran the "level3" command line after entering the processed "custom feature table (from MZmine3)", I encountered the following error prompt. I checked the numerical type of the data box in my 'featureTable' as shown below, which is no different from the numerical type I successfully ran before.
<img width="946" alt="f64f6083cb6af822bacfdefb71dd49c" src="https://github.com/HuanLab/ISFrag/assets/120540244/56c9c049-bfad-4945-a149-30e6b3aecb52">
<img width="649" alt="ea7ca09dce077d14816e12596e98f0e" src="https://github.com/HuanLab/ISFrag/assets/120540244/28c51fb3-6c1a-43af-aa09-174f0c94ebb8">
<img width="637" alt="2880c0139c527b77d59eb49a88bf107" src="https://github.com/HuanLab/ISFrag/assets/120540244/54a7b0c9-3ac9-4bb3-9088-05f60e9e25ff">
Because the data I entered was a list of peaks that I detected after deducting blanks, I manually and selectively deleted a portion (raw data: 23000 rows, including MS2: 15740 rows; detection rate after deducting blanks>0%: 7244 rows). I am not sure if this error was caused by "ISFrag" not finding peaks with peak shape correlation when running "level3". I sincerely hope to receive your answer
